dist: trusty
sudo: required
language: c
compiler:
  - clang
  - gcc
sudo: required
before_install:
  - "sudo add-apt-repository ppa:mraa/mraa -y"
  - "sudo apt-get -qq update"
  - "sudo apt-get install libmraa1 libmraa-dev mraa-tools"
script:
  - "cd ./source"
  - "make"