dist: trusty
sudo: required
language: c
compiler:
  - clang
  - gcc
before_install:
  - "sudo add-apt-repository ppa:mraa/mraa -y"
  - "sudo apt-get -qq update"
  - "sudo apt-get install libmraa1 libmraa-dev mraa-tools"
script:
  - "cd src"
  - "make"