language: c
compiler:
  - clang
  - gcc
# need to install mraa
install: "sudo add-apt-repository ppa:mraa/mraa
sudo apt-get update
sudo apt-get install libmraa1 libmraa-dev mraa-tools python-mraa python3-mraa"
script: make