language: c
compiler:
  - clang
  - gcc
# need to install mraa
sudo: required
before_install:
  - "sudo add-apt-repository ppa:mraa/mraa -y"
  - "sudo apt-get -qq update"
  - "sudo apt-get install libmraa1 libmraa-dev mraa-tools python-mraa python3-mraa"
script:
  - "cd ./source"
  - "make"